-- -------------------------------------------------------------
--
-- Module: HA_Bandpass64
-- Generated by MATLAB(R) 9.1 and the Filter Design HDL Coder 3.1.
-- Generated on: 2017-06-13 12:14:11
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: HA_Bandpass64
-- SerialPartition: [16   7]
-- InputDataType: numerictype(1,32,28)
-- TestBenchName: firfilt_copy_tb
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Partly Serial
-- Folding Factor        : 16
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 65
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s32,32 -> [-5.000000e-01 5.000000e-01)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY HA_Bandpass64 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(31 DOWNTO 0); -- sfix32_En28
         filter_out                      :   OUT   std_logic_vector(70 DOWNTO 0)  -- sfix71_En60
         );

END HA_Bandpass64;


----------------------------------------------------------------
--Module Architecture: HA_Bandpass64
----------------------------------------------------------------
ARCHITECTURE rtl OF HA_Bandpass64 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(31 DOWNTO 0); -- sfix32_En28
  -- Constants
  CONSTANT coeff1                         : signed(31 DOWNTO 0) := to_signed(-5921268, 32); -- sfix32_En32
  CONSTANT coeff2                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff3                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff4                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff5                         : signed(31 DOWNTO 0) := to_signed(9729101, 32); -- sfix32_En32
  CONSTANT coeff6                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff7                         : signed(31 DOWNTO 0) := to_signed(-14349872, 32); -- sfix32_En32
  CONSTANT coeff8                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff9                         : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff10                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff11                        : signed(31 DOWNTO 0) := to_signed(30622396, 32); -- sfix32_En32
  CONSTANT coeff12                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff13                        : signed(31 DOWNTO 0) := to_signed(-43102759, 32); -- sfix32_En32
  CONSTANT coeff14                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff15                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff16                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff17                        : signed(31 DOWNTO 0) := to_signed(79937116, 32); -- sfix32_En32
  CONSTANT coeff18                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff19                        : signed(31 DOWNTO 0) := to_signed(-106539096, 32); -- sfix32_En32
  CONSTANT coeff20                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff21                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff22                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff23                        : signed(31 DOWNTO 0) := to_signed(188429500, 32); -- sfix32_En32
  CONSTANT coeff24                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff25                        : signed(31 DOWNTO 0) := to_signed(-256174510, 32); -- sfix32_En32
  CONSTANT coeff26                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff27                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff28                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff29                        : signed(31 DOWNTO 0) := to_signed(571393218, 32); -- sfix32_En32
  CONSTANT coeff30                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff31                        : signed(31 DOWNTO 0) := to_signed(-1173786221, 32); -- sfix32_En32
  CONSTANT coeff32                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff33                        : signed(31 DOWNTO 0) := to_signed(1431998911, 32); -- sfix32_En32
  CONSTANT coeff34                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff35                        : signed(31 DOWNTO 0) := to_signed(-1173786221, 32); -- sfix32_En32
  CONSTANT coeff36                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff37                        : signed(31 DOWNTO 0) := to_signed(571393218, 32); -- sfix32_En32
  CONSTANT coeff38                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff39                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff40                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff41                        : signed(31 DOWNTO 0) := to_signed(-256174510, 32); -- sfix32_En32
  CONSTANT coeff42                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff43                        : signed(31 DOWNTO 0) := to_signed(188429500, 32); -- sfix32_En32
  CONSTANT coeff44                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff45                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff46                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff47                        : signed(31 DOWNTO 0) := to_signed(-106539096, 32); -- sfix32_En32
  CONSTANT coeff48                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff49                        : signed(31 DOWNTO 0) := to_signed(79937116, 32); -- sfix32_En32
  CONSTANT coeff50                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff51                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff52                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff53                        : signed(31 DOWNTO 0) := to_signed(-43102759, 32); -- sfix32_En32
  CONSTANT coeff54                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff55                        : signed(31 DOWNTO 0) := to_signed(30622396, 32); -- sfix32_En32
  CONSTANT coeff56                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff57                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff58                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff59                        : signed(31 DOWNTO 0) := to_signed(-14349872, 32); -- sfix32_En32
  CONSTANT coeff60                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff61                        : signed(31 DOWNTO 0) := to_signed(9729101, 32); -- sfix32_En32
  CONSTANT coeff62                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff63                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff64                        : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeff65                        : signed(31 DOWNTO 0) := to_signed(-5921268, 32); -- sfix32_En32

  -- Signals
  SIGNAL cur_count                        : unsigned(3 DOWNTO 0); -- ufix4
  SIGNAL phase_15                         : std_logic; -- boolean
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 64); -- sfix32_En28
  SIGNAL inputmux_1                       : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL inputmux_2                       : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL acc_final                        : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL acc_out_1                        : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL product_1                        : signed(63 DOWNTO 0); -- sfix64_En60
  SIGNAL product_1_mux                    : signed(31 DOWNTO 0); -- sfix32_En32
  SIGNAL prod_typeconvert_1               : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL acc_sum_1                        : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL acc_in_1                         : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL add_temp                         : signed(71 DOWNTO 0); -- sfix72_En60
  SIGNAL acc_out_2                        : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL product_2                        : signed(63 DOWNTO 0); -- sfix64_En60
  SIGNAL product_2_mux                    : signed(31 DOWNTO 0); -- sfix32_En32
  SIGNAL prod_typeconvert_2               : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL acc_sum_2                        : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL acc_in_2                         : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL add_temp_1                       : signed(71 DOWNTO 0); -- sfix72_En60
  SIGNAL sum1                             : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL add_temp_2                       : signed(71 DOWNTO 0); -- sfix72_En60
  SIGNAL output_typeconvert               : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL output_register                  : signed(70 DOWNTO 0); -- sfix71_En60


BEGIN

  -- Block Statements
  Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(15, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count = to_unsigned(15, 4) THEN
          cur_count <= to_unsigned(0, 4);
        ELSE
          cur_count <= cur_count + 1;
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter_process;

  phase_15 <= '1' WHEN cur_count = to_unsigned(15, 4) AND clk_enable = '1' ELSE '0';

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 4) AND clk_enable = '1' ELSE '0';

  phase_1 <= '1' WHEN  (((cur_count = to_unsigned(0, 4))  OR
                         (cur_count = to_unsigned(1, 4))  OR
                         (cur_count = to_unsigned(2, 4))  OR
                         (cur_count = to_unsigned(3, 4))  OR
                         (cur_count = to_unsigned(4, 4))  OR
                         (cur_count = to_unsigned(5, 4))  OR
                         (cur_count = to_unsigned(6, 4)))  AND clk_enable = '1') ELSE '0';

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 64) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_15 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 64) <= delay_pipeline(0 TO 63);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  inputmux_1 <= delay_pipeline(0) WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                     delay_pipeline(4) WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                     delay_pipeline(6) WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                     delay_pipeline(10) WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                     delay_pipeline(12) WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                     delay_pipeline(16) WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                     delay_pipeline(18) WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                     delay_pipeline(22) WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                     delay_pipeline(24) WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                     delay_pipeline(28) WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                     delay_pipeline(30) WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                     delay_pipeline(32) WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                     delay_pipeline(34) WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                     delay_pipeline(36) WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                     delay_pipeline(40) WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                     delay_pipeline(42);

  inputmux_2 <= delay_pipeline(46) WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                     delay_pipeline(48) WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                     delay_pipeline(52) WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                     delay_pipeline(54) WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                     delay_pipeline(58) WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                     delay_pipeline(60) WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                     delay_pipeline(64);

  --   ------------------ Serial partition # 1 ------------------

  product_1_mux <= coeff1 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeff5 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeff7 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeff11 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeff13 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeff17 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeff19 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeff23 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeff25 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeff29 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeff31 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeff33 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeff35 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeff37 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeff41 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeff43;
  product_1 <= inputmux_1 * product_1_mux;

  prod_typeconvert_1 <= resize(product_1, 71);

  add_temp <= resize(prod_typeconvert_1, 72) + resize(acc_out_1, 72);
  acc_sum_1 <= add_temp(70 DOWNTO 0);

  acc_in_1 <= prod_typeconvert_1 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_1;

  Acc_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        acc_out_1 <= acc_in_1;
      END IF;
    END IF; 
  END PROCESS Acc_reg_1_process;

  --   ------------------ Serial partition # 2 ------------------

  product_2_mux <= coeff47 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeff49 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeff53 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeff55 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeff59 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeff61 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeff65;
  product_2 <= inputmux_2 * product_2_mux;

  prod_typeconvert_2 <= resize(product_2, 71);

  add_temp_1 <= resize(prod_typeconvert_2, 72) + resize(acc_out_2, 72);
  acc_sum_2 <= add_temp_1(70 DOWNTO 0);

  acc_in_2 <= prod_typeconvert_2 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_2;

  Acc_reg_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        acc_out_2 <= acc_in_2;
      END IF;
    END IF; 
  END PROCESS Acc_reg_2_process;

  add_temp_2 <= resize(acc_out_2, 72) + resize(acc_out_1, 72);
  sum1 <= add_temp_2(70 DOWNTO 0);

  Finalsum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        acc_final <= sum1;
      END IF;
    END IF; 
  END PROCESS Finalsum_reg_process;

  output_typeconvert <= acc_final;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_15 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
