# TCL File Generated by Component Editor 16.0
# Wed May 31 08:36:20 MDT 2017
# DO NOT MODIFY


# 
# FE_Qsys_ZeroStream "FE_Qsys_ZeroStream" v1.0
#  2017.05.31.08:36:20
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module FE_Qsys_ZeroStream
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Qsys_ZeroStream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Qsys_ZeroStream
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_Qsys_ZeroStream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_Qsys_ZeroStream.vhd VHDL PATH ../../DE0/Source_Files/FE_Qsys_ZeroStream.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink sink_data data Input 32
add_interface_port sink sink_error error Input 2
add_interface_port sink sink_valid valid Input 1


# 
# connection point zero_source
# 
add_interface zero_source avalon_streaming start
set_interface_property zero_source associatedClock clock
set_interface_property zero_source associatedReset reset
set_interface_property zero_source dataBitsPerSymbol 8
set_interface_property zero_source errorDescriptor ""
set_interface_property zero_source firstSymbolInHighOrderBits true
set_interface_property zero_source maxChannel 0
set_interface_property zero_source readyLatency 0
set_interface_property zero_source ENABLED true
set_interface_property zero_source EXPORT_OF ""
set_interface_property zero_source PORT_NAME_MAP ""
set_interface_property zero_source CMSIS_SVD_VARIABLES ""
set_interface_property zero_source SVD_ADDRESS_GROUP ""

add_interface_port zero_source source_data data Output 32
add_interface_port zero_source source_error error Output 2
add_interface_port zero_source source_valid valid Output 1

