# TCL File Generated by Component Editor 16.0
# Wed May 10 09:16:21 MDT 2017
# DO NOT MODIFY


# 
# FE_Qsys_AD1939_DE0_Nano "FE_Qsys_AD1939_DE0_Nano" v1.0
#  2017.05.10.09:16:21
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module FE_Qsys_AD1939_DE0_Nano
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Qsys_AD1939_DE0_Nano
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Qsys_AD1939_DE0_Nano
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AD1939_Qsys_DE0_Nano_dcr02
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_Qsys_AD1939_DE0_Nano.vhd VHDL PATH ../../AD1939/Source_Files/FE_Qsys_AD1939_DE0_Nano.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 5
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external
# 
add_interface external conduit end
set_interface_property external associatedClock clock
set_interface_property external associatedReset reset
set_interface_property external ENABLED true
set_interface_property external EXPORT_OF ""
set_interface_property external PORT_NAME_MAP ""
set_interface_property external CMSIS_SVD_VARIABLES ""
set_interface_property external SVD_ADDRESS_GROUP ""

add_interface_port external AD1939_SPI_CIN ad1939_spi_cin Output 1
add_interface_port external AD1939_SPI_COUT ad1939_spi_cout Input 1
add_interface_port external AD1939_SPI_CCLK ad1939_spi_cclk Output 1
add_interface_port external AD1939_SPI_CLATCH_n ad1939_spi_clatch_n Output 1
add_interface_port external AD1939_ADC_SDATA1 ad1939_adc_sdata1 Input 1
add_interface_port external AD1939_ADC_SDATA2 ad1939_adc_sdata2 Input 1
add_interface_port external AD1939_ADC_BCLK ad1939_adc_bclk Input 1
add_interface_port external AD1939_ADC_LRCLK ad1939_adc_lrclk Input 1
add_interface_port external AD1939_DAC_SDATA1 ad1939_dac_sdata1 Output 1
add_interface_port external AD1939_DAC_SDATA2 ad1939_dac_sdata2 Output 1
add_interface_port external AD1939_DAC_SDATA3 ad1939_dac_sdata3 Output 1
add_interface_port external AD1939_DAC_SDATA4 ad1939_dac_sdata4 Output 1
add_interface_port external AD1939_DAC_BCLK ad1939_dac_bclk Output 1
add_interface_port external AD1939_DAC_LRCLK ad1939_dac_lrclk Output 1


# 
# connection point Line_Out_Right
# 
add_interface Line_Out_Right avalon_streaming end
set_interface_property Line_Out_Right associatedClock clock
set_interface_property Line_Out_Right associatedReset reset
set_interface_property Line_Out_Right dataBitsPerSymbol 8
set_interface_property Line_Out_Right errorDescriptor ""
set_interface_property Line_Out_Right firstSymbolInHighOrderBits true
set_interface_property Line_Out_Right maxChannel 0
set_interface_property Line_Out_Right readyLatency 0
set_interface_property Line_Out_Right ENABLED true
set_interface_property Line_Out_Right EXPORT_OF ""
set_interface_property Line_Out_Right PORT_NAME_MAP ""
set_interface_property Line_Out_Right CMSIS_SVD_VARIABLES ""
set_interface_property Line_Out_Right SVD_ADDRESS_GROUP ""

add_interface_port Line_Out_Right Line_Out_right_data data Input 32
add_interface_port Line_Out_Right Line_Out_right_error error Input 2
add_interface_port Line_Out_Right Line_Out_right_valid valid Input 1


# 
# connection point Line_Out_Left
# 
add_interface Line_Out_Left avalon_streaming end
set_interface_property Line_Out_Left associatedClock clock
set_interface_property Line_Out_Left associatedReset reset
set_interface_property Line_Out_Left dataBitsPerSymbol 8
set_interface_property Line_Out_Left errorDescriptor ""
set_interface_property Line_Out_Left firstSymbolInHighOrderBits true
set_interface_property Line_Out_Left maxChannel 0
set_interface_property Line_Out_Left readyLatency 0
set_interface_property Line_Out_Left ENABLED true
set_interface_property Line_Out_Left EXPORT_OF ""
set_interface_property Line_Out_Left PORT_NAME_MAP ""
set_interface_property Line_Out_Left CMSIS_SVD_VARIABLES ""
set_interface_property Line_Out_Left SVD_ADDRESS_GROUP ""

add_interface_port Line_Out_Left Line_Out_left_data data Input 32
add_interface_port Line_Out_Left Line_Out_left_error error Input 2
add_interface_port Line_Out_Left Line_Out_left_valid valid Input 1


# 
# connection point Headphone_Out_Right
# 
add_interface Headphone_Out_Right avalon_streaming end
set_interface_property Headphone_Out_Right associatedClock clock
set_interface_property Headphone_Out_Right associatedReset reset
set_interface_property Headphone_Out_Right dataBitsPerSymbol 8
set_interface_property Headphone_Out_Right errorDescriptor ""
set_interface_property Headphone_Out_Right firstSymbolInHighOrderBits true
set_interface_property Headphone_Out_Right maxChannel 0
set_interface_property Headphone_Out_Right readyLatency 0
set_interface_property Headphone_Out_Right ENABLED true
set_interface_property Headphone_Out_Right EXPORT_OF ""
set_interface_property Headphone_Out_Right PORT_NAME_MAP ""
set_interface_property Headphone_Out_Right CMSIS_SVD_VARIABLES ""
set_interface_property Headphone_Out_Right SVD_ADDRESS_GROUP ""

add_interface_port Headphone_Out_Right Headphone_Out_right_data data Input 32
add_interface_port Headphone_Out_Right Headphone_Out_right_error error Input 2
add_interface_port Headphone_Out_Right Headphone_Out_right_valid valid Input 1


# 
# connection point Headphone_Out_Left
# 
add_interface Headphone_Out_Left avalon_streaming end
set_interface_property Headphone_Out_Left associatedClock clock
set_interface_property Headphone_Out_Left associatedReset reset
set_interface_property Headphone_Out_Left dataBitsPerSymbol 8
set_interface_property Headphone_Out_Left errorDescriptor ""
set_interface_property Headphone_Out_Left firstSymbolInHighOrderBits true
set_interface_property Headphone_Out_Left maxChannel 0
set_interface_property Headphone_Out_Left readyLatency 0
set_interface_property Headphone_Out_Left ENABLED true
set_interface_property Headphone_Out_Left EXPORT_OF ""
set_interface_property Headphone_Out_Left PORT_NAME_MAP ""
set_interface_property Headphone_Out_Left CMSIS_SVD_VARIABLES ""
set_interface_property Headphone_Out_Left SVD_ADDRESS_GROUP ""

add_interface_port Headphone_Out_Left Headphone_Out_left_data data Input 32
add_interface_port Headphone_Out_Left Headphone_Out_left_error error Input 2
add_interface_port Headphone_Out_Left Headphone_Out_left_valid valid Input 1


# 
# connection point Line_In_Right
# 
add_interface Line_In_Right avalon_streaming start
set_interface_property Line_In_Right associatedClock clock
set_interface_property Line_In_Right associatedReset reset
set_interface_property Line_In_Right dataBitsPerSymbol 8
set_interface_property Line_In_Right errorDescriptor ""
set_interface_property Line_In_Right firstSymbolInHighOrderBits true
set_interface_property Line_In_Right maxChannel 0
set_interface_property Line_In_Right readyLatency 0
set_interface_property Line_In_Right ENABLED true
set_interface_property Line_In_Right EXPORT_OF ""
set_interface_property Line_In_Right PORT_NAME_MAP ""
set_interface_property Line_In_Right CMSIS_SVD_VARIABLES ""
set_interface_property Line_In_Right SVD_ADDRESS_GROUP ""

add_interface_port Line_In_Right Line_In_right_data data Output 32
add_interface_port Line_In_Right Line_In_right_error error Output 2
add_interface_port Line_In_Right Line_In_right_valid valid Output 1


# 
# connection point Mic_In_Left
# 
add_interface Mic_In_Left avalon_streaming start
set_interface_property Mic_In_Left associatedClock clock
set_interface_property Mic_In_Left associatedReset reset
set_interface_property Mic_In_Left dataBitsPerSymbol 8
set_interface_property Mic_In_Left errorDescriptor ""
set_interface_property Mic_In_Left firstSymbolInHighOrderBits true
set_interface_property Mic_In_Left maxChannel 0
set_interface_property Mic_In_Left readyLatency 0
set_interface_property Mic_In_Left ENABLED true
set_interface_property Mic_In_Left EXPORT_OF ""
set_interface_property Mic_In_Left PORT_NAME_MAP ""
set_interface_property Mic_In_Left CMSIS_SVD_VARIABLES ""
set_interface_property Mic_In_Left SVD_ADDRESS_GROUP ""

add_interface_port Mic_In_Left Mic_In_left_data data Output 32
add_interface_port Mic_In_Left Mic_In_left_error error Output 2
add_interface_port Mic_In_Left Mic_In_left_valid valid Output 1


# 
# connection point Mic_In_Right
# 
add_interface Mic_In_Right avalon_streaming start
set_interface_property Mic_In_Right associatedClock clock
set_interface_property Mic_In_Right associatedReset reset
set_interface_property Mic_In_Right dataBitsPerSymbol 8
set_interface_property Mic_In_Right errorDescriptor ""
set_interface_property Mic_In_Right firstSymbolInHighOrderBits true
set_interface_property Mic_In_Right maxChannel 0
set_interface_property Mic_In_Right readyLatency 0
set_interface_property Mic_In_Right ENABLED true
set_interface_property Mic_In_Right EXPORT_OF ""
set_interface_property Mic_In_Right PORT_NAME_MAP ""
set_interface_property Mic_In_Right CMSIS_SVD_VARIABLES ""
set_interface_property Mic_In_Right SVD_ADDRESS_GROUP ""

add_interface_port Mic_In_Right Mic_In_right_data data Output 32
add_interface_port Mic_In_Right Mic_In_right_error error Output 2
add_interface_port Mic_In_Right Mic_In_right_valid valid Output 1


# 
# connection point Line_In_Left
# 
add_interface Line_In_Left avalon_streaming start
set_interface_property Line_In_Left associatedClock clock
set_interface_property Line_In_Left associatedReset reset
set_interface_property Line_In_Left dataBitsPerSymbol 8
set_interface_property Line_In_Left errorDescriptor ""
set_interface_property Line_In_Left firstSymbolInHighOrderBits true
set_interface_property Line_In_Left maxChannel 0
set_interface_property Line_In_Left readyLatency 0
set_interface_property Line_In_Left ENABLED true
set_interface_property Line_In_Left EXPORT_OF ""
set_interface_property Line_In_Left PORT_NAME_MAP ""
set_interface_property Line_In_Left CMSIS_SVD_VARIABLES ""
set_interface_property Line_In_Left SVD_ADDRESS_GROUP ""

add_interface_port Line_In_Left Line_In_left_data data Output 32
add_interface_port Line_In_Left Line_In_left_error error Output 2
add_interface_port Line_In_Left Line_In_left_valid valid Output 1

