# TCL File Generated by Component Editor 16.0
# Tue Jun 13 08:22:04 MDT 2017
# DO NOT MODIFY


# 
# FE_Qsys_InputMux "FE_Qsys_InputMux" v1.0
#  2017.06.13.08:22:04
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module FE_Qsys_InputMux
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Qsys_InputMux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Qsys_InputMux
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_QSys_InputMux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_QSys_InputMux.vhd VHDL PATH FE_QSys_InputMux.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DEFAULT_SOURCE INTEGER 1 "Default souce to select on startup"
set_parameter_property DEFAULT_SOURCE DEFAULT_VALUE 1
set_parameter_property DEFAULT_SOURCE DISPLAY_NAME DEFAULT_SOURCE
set_parameter_property DEFAULT_SOURCE TYPE INTEGER
set_parameter_property DEFAULT_SOURCE UNITS None
set_parameter_property DEFAULT_SOURCE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_SOURCE DESCRIPTION "Default souce to select on startup"
set_parameter_property DEFAULT_SOURCE HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible dev,fe-input-mux
set_module_assignment embeddedsw.dts.group input-mux
set_module_assignment embeddedsw.dts.vendor fe


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 4
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point in1_left
# 
add_interface in1_left avalon_streaming end
set_interface_property in1_left associatedClock clock
set_interface_property in1_left associatedReset reset
set_interface_property in1_left dataBitsPerSymbol 8
set_interface_property in1_left errorDescriptor ""
set_interface_property in1_left firstSymbolInHighOrderBits true
set_interface_property in1_left maxChannel 0
set_interface_property in1_left readyLatency 0
set_interface_property in1_left ENABLED true
set_interface_property in1_left EXPORT_OF ""
set_interface_property in1_left PORT_NAME_MAP ""
set_interface_property in1_left CMSIS_SVD_VARIABLES ""
set_interface_property in1_left SVD_ADDRESS_GROUP ""

add_interface_port in1_left ast_sink_data_1_l data Input 32
add_interface_port in1_left ast_sink_error_1_l error Input 2
add_interface_port in1_left ast_sink_valid_1_l valid Input 1


# 
# connection point in1_right
# 
add_interface in1_right avalon_streaming end
set_interface_property in1_right associatedClock clock
set_interface_property in1_right associatedReset reset
set_interface_property in1_right dataBitsPerSymbol 8
set_interface_property in1_right errorDescriptor ""
set_interface_property in1_right firstSymbolInHighOrderBits true
set_interface_property in1_right maxChannel 0
set_interface_property in1_right readyLatency 0
set_interface_property in1_right ENABLED true
set_interface_property in1_right EXPORT_OF ""
set_interface_property in1_right PORT_NAME_MAP ""
set_interface_property in1_right CMSIS_SVD_VARIABLES ""
set_interface_property in1_right SVD_ADDRESS_GROUP ""

add_interface_port in1_right ast_sink_data_1_r data Input 32
add_interface_port in1_right ast_sink_error_1_r error Input 2
add_interface_port in1_right ast_sink_valid_1_r valid Input 1


# 
# connection point in2_left
# 
add_interface in2_left avalon_streaming end
set_interface_property in2_left associatedClock clock
set_interface_property in2_left associatedReset reset
set_interface_property in2_left dataBitsPerSymbol 8
set_interface_property in2_left errorDescriptor ""
set_interface_property in2_left firstSymbolInHighOrderBits true
set_interface_property in2_left maxChannel 0
set_interface_property in2_left readyLatency 0
set_interface_property in2_left ENABLED true
set_interface_property in2_left EXPORT_OF ""
set_interface_property in2_left PORT_NAME_MAP ""
set_interface_property in2_left CMSIS_SVD_VARIABLES ""
set_interface_property in2_left SVD_ADDRESS_GROUP ""

add_interface_port in2_left ast_sink_data_2_l data Input 32
add_interface_port in2_left ast_sink_error_2_l error Input 2
add_interface_port in2_left ast_sink_valid_2_l valid Input 1


# 
# connection point in2_right
# 
add_interface in2_right avalon_streaming end
set_interface_property in2_right associatedClock clock
set_interface_property in2_right associatedReset reset
set_interface_property in2_right dataBitsPerSymbol 8
set_interface_property in2_right errorDescriptor ""
set_interface_property in2_right firstSymbolInHighOrderBits true
set_interface_property in2_right maxChannel 0
set_interface_property in2_right readyLatency 0
set_interface_property in2_right ENABLED true
set_interface_property in2_right EXPORT_OF ""
set_interface_property in2_right PORT_NAME_MAP ""
set_interface_property in2_right CMSIS_SVD_VARIABLES ""
set_interface_property in2_right SVD_ADDRESS_GROUP ""

add_interface_port in2_right ast_sink_data_2_r data Input 32
add_interface_port in2_right ast_sink_error_2_r error Input 2
add_interface_port in2_right ast_sink_valid_2_r valid Input 1


# 
# connection point out_left
# 
add_interface out_left avalon_streaming start
set_interface_property out_left associatedClock clock
set_interface_property out_left associatedReset reset
set_interface_property out_left dataBitsPerSymbol 8
set_interface_property out_left errorDescriptor ""
set_interface_property out_left firstSymbolInHighOrderBits true
set_interface_property out_left maxChannel 0
set_interface_property out_left readyLatency 0
set_interface_property out_left ENABLED true
set_interface_property out_left EXPORT_OF ""
set_interface_property out_left PORT_NAME_MAP ""
set_interface_property out_left CMSIS_SVD_VARIABLES ""
set_interface_property out_left SVD_ADDRESS_GROUP ""

add_interface_port out_left ast_source_data_l data Output 32
add_interface_port out_left ast_source_error_l error Output 2
add_interface_port out_left ast_source_valid_l valid Output 1


# 
# connection point out_right
# 
add_interface out_right avalon_streaming start
set_interface_property out_right associatedClock clock
set_interface_property out_right associatedReset reset
set_interface_property out_right dataBitsPerSymbol 8
set_interface_property out_right errorDescriptor ""
set_interface_property out_right firstSymbolInHighOrderBits true
set_interface_property out_right maxChannel 0
set_interface_property out_right readyLatency 0
set_interface_property out_right ENABLED true
set_interface_property out_right EXPORT_OF ""
set_interface_property out_right PORT_NAME_MAP ""
set_interface_property out_right CMSIS_SVD_VARIABLES ""
set_interface_property out_right SVD_ADDRESS_GROUP ""

add_interface_port out_right ast_source_data_r data Output 32
add_interface_port out_right ast_source_valid_r valid Output 1
add_interface_port out_right ast_source_error_r error Output 2

