# TCL File Generated by Component Editor 16.0
# Wed May 10 11:21:07 MDT 2017
# DO NOT MODIFY


# 
# FE_Qsys_DownUpBy2 "FE_Qsys_DownUpBy2" v1.0
#  2017.05.10.11:21:07
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module FE_Qsys_DownUpBy2
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Qsys_DownUpBy2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Qsys_DownUpBy2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_Qsys_DownUpBy2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_Qsys_DownUpBy2.vhd VHDL PATH ../Source_Files/FE_Qsys_DownUpBy2.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FIR_MIF_FileName_up STRING FE_MIF_FIR_UpSampleBy2.mif
set_parameter_property FIR_MIF_FileName_up DEFAULT_VALUE FE_MIF_FIR_UpSampleBy2.mif
set_parameter_property FIR_MIF_FileName_up DISPLAY_NAME FIR_MIF_FileName_up
set_parameter_property FIR_MIF_FileName_up TYPE STRING
set_parameter_property FIR_MIF_FileName_up UNITS None
set_parameter_property FIR_MIF_FileName_up HDL_PARAMETER true
add_parameter FIR_MIF_FileName_down STRING FE_MIF_FIR_DownSampleBy2.mif
set_parameter_property FIR_MIF_FileName_down DEFAULT_VALUE FE_MIF_FIR_DownSampleBy2.mif
set_parameter_property FIR_MIF_FileName_down DISPLAY_NAME FIR_MIF_FileName_down
set_parameter_property FIR_MIF_FileName_down TYPE STRING
set_parameter_property FIR_MIF_FileName_down UNITS None
set_parameter_property FIR_MIF_FileName_down HDL_PARAMETER true
add_parameter FIR_Max_Coefs INTEGER 64
set_parameter_property FIR_Max_Coefs DEFAULT_VALUE 64
set_parameter_property FIR_Max_Coefs DISPLAY_NAME FIR_Max_Coefs
set_parameter_property FIR_Max_Coefs TYPE INTEGER
set_parameter_property FIR_Max_Coefs UNITS None
set_parameter_property FIR_Max_Coefs HDL_PARAMETER true
add_parameter FIR_Addr_Width INTEGER 7
set_parameter_property FIR_Addr_Width DEFAULT_VALUE 7
set_parameter_property FIR_Addr_Width DISPLAY_NAME FIR_Addr_Width
set_parameter_property FIR_Addr_Width TYPE INTEGER
set_parameter_property FIR_Addr_Width UNITS None
set_parameter_property FIR_Addr_Width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input fir_addr_width
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point to_downsampler
# 
add_interface to_downsampler avalon_streaming end
set_interface_property to_downsampler associatedClock clock
set_interface_property to_downsampler associatedReset reset
set_interface_property to_downsampler dataBitsPerSymbol 8
set_interface_property to_downsampler errorDescriptor ""
set_interface_property to_downsampler firstSymbolInHighOrderBits true
set_interface_property to_downsampler maxChannel 0
set_interface_property to_downsampler readyLatency 0
set_interface_property to_downsampler ENABLED true
set_interface_property to_downsampler EXPORT_OF ""
set_interface_property to_downsampler PORT_NAME_MAP ""
set_interface_property to_downsampler CMSIS_SVD_VARIABLES ""
set_interface_property to_downsampler SVD_ADDRESS_GROUP ""

add_interface_port to_downsampler to_downsampler_data data Input 32
add_interface_port to_downsampler to_downsampler_error error Input 2
add_interface_port to_downsampler to_downsampler_valid valid Input 1


# 
# connection point to_Upsampler
# 
add_interface to_Upsampler avalon_streaming end
set_interface_property to_Upsampler associatedClock clock
set_interface_property to_Upsampler associatedReset reset
set_interface_property to_Upsampler dataBitsPerSymbol 8
set_interface_property to_Upsampler errorDescriptor ""
set_interface_property to_Upsampler firstSymbolInHighOrderBits true
set_interface_property to_Upsampler maxChannel 0
set_interface_property to_Upsampler readyLatency 0
set_interface_property to_Upsampler ENABLED true
set_interface_property to_Upsampler EXPORT_OF ""
set_interface_property to_Upsampler PORT_NAME_MAP ""
set_interface_property to_Upsampler CMSIS_SVD_VARIABLES ""
set_interface_property to_Upsampler SVD_ADDRESS_GROUP ""

add_interface_port to_Upsampler to_Upsampler_data data Input 32
add_interface_port to_Upsampler to_Upsampler_error error Input 2
add_interface_port to_Upsampler to_Upsampler_valid valid Input 1


# 
# connection point Downsampled
# 
add_interface Downsampled avalon_streaming start
set_interface_property Downsampled associatedClock clock
set_interface_property Downsampled associatedReset reset
set_interface_property Downsampled dataBitsPerSymbol 8
set_interface_property Downsampled errorDescriptor ""
set_interface_property Downsampled firstSymbolInHighOrderBits true
set_interface_property Downsampled maxChannel 0
set_interface_property Downsampled readyLatency 0
set_interface_property Downsampled ENABLED true
set_interface_property Downsampled EXPORT_OF ""
set_interface_property Downsampled PORT_NAME_MAP ""
set_interface_property Downsampled CMSIS_SVD_VARIABLES ""
set_interface_property Downsampled SVD_ADDRESS_GROUP ""

add_interface_port Downsampled downsampled_data data Output 32
add_interface_port Downsampled downsampled_error error Output 2
add_interface_port Downsampled downsampled_valid valid Output 1


# 
# connection point Upsampled
# 
add_interface Upsampled avalon_streaming start
set_interface_property Upsampled associatedClock clock
set_interface_property Upsampled associatedReset reset
set_interface_property Upsampled dataBitsPerSymbol 8
set_interface_property Upsampled errorDescriptor ""
set_interface_property Upsampled firstSymbolInHighOrderBits true
set_interface_property Upsampled maxChannel 0
set_interface_property Upsampled readyLatency 0
set_interface_property Upsampled ENABLED true
set_interface_property Upsampled EXPORT_OF ""
set_interface_property Upsampled PORT_NAME_MAP ""
set_interface_property Upsampled CMSIS_SVD_VARIABLES ""
set_interface_property Upsampled SVD_ADDRESS_GROUP ""

add_interface_port Upsampled Upsampled_data data Output 32
add_interface_port Upsampled Upsampled_error error Output 2
add_interface_port Upsampled Upsampled_valid valid Output 1

