# TCL File Generated by Component Editor 16.0
# Mon May 29 13:27:12 MDT 2017
# DO NOT MODIFY


# 
# FE_Qsys_DownUpBy2_v3 "FE_Qsys_DownUpBy2_v3" v1.0
#  2017.05.29.13:27:12
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module FE_Qsys_DownUpBy2_v3
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Qsys_DownUpBy2_v3
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Qsys_DownUpBy2_v3
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_Qsys_DownUpBy2_v3
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_Qsys_DownUpBy2_v3.vhd VHDL PATH ../../DE0/Source_Files/FE_Qsys_DownUpBy2_v3.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FIR_MIF_FileName_up STRING FE_MIF_FIR_UpSampleBy2.mif
set_parameter_property FIR_MIF_FileName_up DEFAULT_VALUE FE_MIF_FIR_UpSampleBy2.mif
set_parameter_property FIR_MIF_FileName_up DISPLAY_NAME FIR_MIF_FileName_up
set_parameter_property FIR_MIF_FileName_up TYPE STRING
set_parameter_property FIR_MIF_FileName_up UNITS None
set_parameter_property FIR_MIF_FileName_up HDL_PARAMETER true
add_parameter FIR_MIF_FileName_down STRING FE_MIF_FIR_DownSampleBy2.mif
set_parameter_property FIR_MIF_FileName_down DEFAULT_VALUE FE_MIF_FIR_DownSampleBy2.mif
set_parameter_property FIR_MIF_FileName_down DISPLAY_NAME FIR_MIF_FileName_down
set_parameter_property FIR_MIF_FileName_down TYPE STRING
set_parameter_property FIR_MIF_FileName_down UNITS None
set_parameter_property FIR_MIF_FileName_down HDL_PARAMETER true
add_parameter FIR_Max_Coefs INTEGER 256
set_parameter_property FIR_Max_Coefs DEFAULT_VALUE 256
set_parameter_property FIR_Max_Coefs DISPLAY_NAME FIR_Max_Coefs
set_parameter_property FIR_Max_Coefs TYPE INTEGER
set_parameter_property FIR_Max_Coefs UNITS None
set_parameter_property FIR_Max_Coefs HDL_PARAMETER true
add_parameter FIR_Addr_Width INTEGER 8
set_parameter_property FIR_Addr_Width DEFAULT_VALUE 8
set_parameter_property FIR_Addr_Width DISPLAY_NAME FIR_Addr_Width
set_parameter_property FIR_Addr_Width TYPE INTEGER
set_parameter_property FIR_Addr_Width UNITS None
set_parameter_property FIR_Addr_Width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input fir_addr_width
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point s2
# 
add_interface s2 avalon end
set_interface_property s2 addressUnits WORDS
set_interface_property s2 associatedClock clock
set_interface_property s2 associatedReset reset
set_interface_property s2 bitsPerSymbol 8
set_interface_property s2 burstOnBurstBoundariesOnly false
set_interface_property s2 burstcountUnits WORDS
set_interface_property s2 explicitAddressSpan 0
set_interface_property s2 holdTime 0
set_interface_property s2 linewrapBursts false
set_interface_property s2 maximumPendingReadTransactions 0
set_interface_property s2 maximumPendingWriteTransactions 0
set_interface_property s2 readLatency 0
set_interface_property s2 readWaitTime 1
set_interface_property s2 setupTime 0
set_interface_property s2 timingUnits Cycles
set_interface_property s2 writeWaitTime 0
set_interface_property s2 ENABLED true
set_interface_property s2 EXPORT_OF ""
set_interface_property s2 PORT_NAME_MAP ""
set_interface_property s2 CMSIS_SVD_VARIABLES ""
set_interface_property s2 SVD_ADDRESS_GROUP ""

add_interface_port s2 avs_s2_address address Input fir_addr_width
add_interface_port s2 avs_s2_write write Input 1
add_interface_port s2 avs_s2_writedata writedata Input 32
add_interface_port s2 avs_s2_read read Input 1
add_interface_port s2 avs_s2_readdata readdata Output 32
set_interface_assignment s2 embeddedsw.configuration.isFlash 0
set_interface_assignment s2 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s2 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s2 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point DownSampled_ch1
# 
add_interface DownSampled_ch1 avalon_streaming start
set_interface_property DownSampled_ch1 associatedClock clock
set_interface_property DownSampled_ch1 associatedReset reset
set_interface_property DownSampled_ch1 dataBitsPerSymbol 8
set_interface_property DownSampled_ch1 errorDescriptor ""
set_interface_property DownSampled_ch1 firstSymbolInHighOrderBits true
set_interface_property DownSampled_ch1 maxChannel 0
set_interface_property DownSampled_ch1 readyLatency 0
set_interface_property DownSampled_ch1 ENABLED true
set_interface_property DownSampled_ch1 EXPORT_OF ""
set_interface_property DownSampled_ch1 PORT_NAME_MAP ""
set_interface_property DownSampled_ch1 CMSIS_SVD_VARIABLES ""
set_interface_property DownSampled_ch1 SVD_ADDRESS_GROUP ""

add_interface_port DownSampled_ch1 downsampled_ch1_data data Output 32
add_interface_port DownSampled_ch1 downsampled_ch1_error error Output 2
add_interface_port DownSampled_ch1 downsampled_ch1_valid valid Output 1


# 
# connection point UpSampled
# 
add_interface UpSampled avalon_streaming start
set_interface_property UpSampled associatedClock clock
set_interface_property UpSampled associatedReset reset
set_interface_property UpSampled dataBitsPerSymbol 8
set_interface_property UpSampled errorDescriptor ""
set_interface_property UpSampled firstSymbolInHighOrderBits true
set_interface_property UpSampled maxChannel 0
set_interface_property UpSampled readyLatency 0
set_interface_property UpSampled ENABLED true
set_interface_property UpSampled EXPORT_OF ""
set_interface_property UpSampled PORT_NAME_MAP ""
set_interface_property UpSampled CMSIS_SVD_VARIABLES ""
set_interface_property UpSampled SVD_ADDRESS_GROUP ""

add_interface_port UpSampled Upsampled_data data Output 32
add_interface_port UpSampled Upsampled_error error Output 2
add_interface_port UpSampled Upsampled_valid valid Output 1


# 
# connection point DownSampled_ch2
# 
add_interface DownSampled_ch2 avalon_streaming start
set_interface_property DownSampled_ch2 associatedClock clock
set_interface_property DownSampled_ch2 associatedReset reset
set_interface_property DownSampled_ch2 dataBitsPerSymbol 8
set_interface_property DownSampled_ch2 errorDescriptor ""
set_interface_property DownSampled_ch2 firstSymbolInHighOrderBits true
set_interface_property DownSampled_ch2 maxChannel 0
set_interface_property DownSampled_ch2 readyLatency 0
set_interface_property DownSampled_ch2 ENABLED true
set_interface_property DownSampled_ch2 EXPORT_OF ""
set_interface_property DownSampled_ch2 PORT_NAME_MAP ""
set_interface_property DownSampled_ch2 CMSIS_SVD_VARIABLES ""
set_interface_property DownSampled_ch2 SVD_ADDRESS_GROUP ""

add_interface_port DownSampled_ch2 downsampled_ch2_data data Output 32
add_interface_port DownSampled_ch2 downsampled_ch2_error error Output 2
add_interface_port DownSampled_ch2 downsampled_ch2_valid valid Output 1


# 
# connection point to_UpSampler_ch2
# 
add_interface to_UpSampler_ch2 avalon_streaming end
set_interface_property to_UpSampler_ch2 associatedClock clock
set_interface_property to_UpSampler_ch2 associatedReset reset
set_interface_property to_UpSampler_ch2 dataBitsPerSymbol 8
set_interface_property to_UpSampler_ch2 errorDescriptor ""
set_interface_property to_UpSampler_ch2 firstSymbolInHighOrderBits true
set_interface_property to_UpSampler_ch2 maxChannel 0
set_interface_property to_UpSampler_ch2 readyLatency 0
set_interface_property to_UpSampler_ch2 ENABLED true
set_interface_property to_UpSampler_ch2 EXPORT_OF ""
set_interface_property to_UpSampler_ch2 PORT_NAME_MAP ""
set_interface_property to_UpSampler_ch2 CMSIS_SVD_VARIABLES ""
set_interface_property to_UpSampler_ch2 SVD_ADDRESS_GROUP ""

add_interface_port to_UpSampler_ch2 to_Upsampler_ch2_data data Input 32
add_interface_port to_UpSampler_ch2 to_Upsampler_ch2_error error Input 2
add_interface_port to_UpSampler_ch2 to_Upsampler_ch2_valid valid Input 1


# 
# connection point to_UpSampler_ch1
# 
add_interface to_UpSampler_ch1 avalon_streaming end
set_interface_property to_UpSampler_ch1 associatedClock clock
set_interface_property to_UpSampler_ch1 associatedReset reset
set_interface_property to_UpSampler_ch1 dataBitsPerSymbol 8
set_interface_property to_UpSampler_ch1 errorDescriptor ""
set_interface_property to_UpSampler_ch1 firstSymbolInHighOrderBits true
set_interface_property to_UpSampler_ch1 maxChannel 0
set_interface_property to_UpSampler_ch1 readyLatency 0
set_interface_property to_UpSampler_ch1 ENABLED true
set_interface_property to_UpSampler_ch1 EXPORT_OF ""
set_interface_property to_UpSampler_ch1 PORT_NAME_MAP ""
set_interface_property to_UpSampler_ch1 CMSIS_SVD_VARIABLES ""
set_interface_property to_UpSampler_ch1 SVD_ADDRESS_GROUP ""

add_interface_port to_UpSampler_ch1 to_Upsampler_ch1_data data Input 32
add_interface_port to_UpSampler_ch1 to_Upsampler_ch1_error error Input 2
add_interface_port to_UpSampler_ch1 to_Upsampler_ch1_valid valid Input 1


# 
# connection point to_DownSampler
# 
add_interface to_DownSampler avalon_streaming end
set_interface_property to_DownSampler associatedClock clock
set_interface_property to_DownSampler associatedReset reset
set_interface_property to_DownSampler dataBitsPerSymbol 8
set_interface_property to_DownSampler errorDescriptor ""
set_interface_property to_DownSampler firstSymbolInHighOrderBits true
set_interface_property to_DownSampler maxChannel 0
set_interface_property to_DownSampler readyLatency 0
set_interface_property to_DownSampler ENABLED true
set_interface_property to_DownSampler EXPORT_OF ""
set_interface_property to_DownSampler PORT_NAME_MAP ""
set_interface_property to_DownSampler CMSIS_SVD_VARIABLES ""
set_interface_property to_DownSampler SVD_ADDRESS_GROUP ""

add_interface_port to_DownSampler to_downsampler_data data Input 32
add_interface_port to_DownSampler to_downsampler_error error Input 2
add_interface_port to_DownSampler to_downsampler_valid valid Input 1

