-- -------------------------------------------------------------
--
-- Module: FIR128_InterpolateBy2
-- Generated by MATLAB(R) 9.2 and the Filter Design HDL Coder 3.1.1.
-- Generated on: 2017-06-11 09:13:41
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: FIR128_InterpolateBy2
-- SerialPartition: [16  16]
-- InputDataType: numerictype(1,32,28)
-- TestBenchName: firinterp_copy_tb
-- TestBenchStimulus: step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Partly Serial
-- Folding Factor        : 16
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure      : Direct-Form FIR Polyphase Interpolator
-- Interpolation Factor  : 2
-- Polyphase Length      : 65
-- Filter Length         : 129
-- Stable                : Yes
-- Linear Phase          : Yes (Type 1)
--
-- Arithmetic            : fixed
-- Numerator             : s32,32 -> [-5.000000e-01 5.000000e-01)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY FIR128_InterpolateBy2 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(31 DOWNTO 0); -- sfix32_En28
         filter_out                      :   OUT   std_logic_vector(70 DOWNTO 0); -- sfix71_En60
         ce_out                          :   OUT   std_logic  
         );

END FIR128_InterpolateBy2;


----------------------------------------------------------------
--Module Architecture: FIR128_InterpolateBy2
----------------------------------------------------------------
ARCHITECTURE rtl OF FIR128_InterpolateBy2 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(31 DOWNTO 0); -- sfix32_En28
  -- Constants
  CONSTANT coeffphase1_1                  : signed(31 DOWNTO 0) := to_signed(1315991, 32); -- sfix32_En32
  CONSTANT coeffphase1_2                  : signed(31 DOWNTO 0) := to_signed(-1240297, 32); -- sfix32_En32
  CONSTANT coeffphase1_3                  : signed(31 DOWNTO 0) := to_signed(1189139, 32); -- sfix32_En32
  CONSTANT coeffphase1_4                  : signed(31 DOWNTO 0) := to_signed(-1132720, 32); -- sfix32_En32
  CONSTANT coeffphase1_5                  : signed(31 DOWNTO 0) := to_signed(1033060, 32); -- sfix32_En32
  CONSTANT coeffphase1_6                  : signed(31 DOWNTO 0) := to_signed(-845192, 32); -- sfix32_En32
  CONSTANT coeffphase1_7                  : signed(31 DOWNTO 0) := to_signed(518767, 32); -- sfix32_En32
  CONSTANT coeffphase1_8                  : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeffphase1_9                  : signed(31 DOWNTO 0) := to_signed(-766094, 32); -- sfix32_En32
  CONSTANT coeffphase1_10                 : signed(31 DOWNTO 0) := to_signed(1833277, 32); -- sfix32_En32
  CONSTANT coeffphase1_11                 : signed(31 DOWNTO 0) := to_signed(-3251561, 32); -- sfix32_En32
  CONSTANT coeffphase1_12                 : signed(31 DOWNTO 0) := to_signed(5064688, 32); -- sfix32_En32
  CONSTANT coeffphase1_13                 : signed(31 DOWNTO 0) := to_signed(-7307718, 32); -- sfix32_En32
  CONSTANT coeffphase1_14                 : signed(31 DOWNTO 0) := to_signed(10004835, 32); -- sfix32_En32
  CONSTANT coeffphase1_15                 : signed(31 DOWNTO 0) := to_signed(-13167465, 32); -- sfix32_En32
  CONSTANT coeffphase1_16                 : signed(31 DOWNTO 0) := to_signed(16792796, 32); -- sfix32_En32
  CONSTANT coeffphase1_17                 : signed(31 DOWNTO 0) := to_signed(-20862774, 32); -- sfix32_En32
  CONSTANT coeffphase1_18                 : signed(31 DOWNTO 0) := to_signed(25343633, 32); -- sfix32_En32
  CONSTANT coeffphase1_19                 : signed(31 DOWNTO 0) := to_signed(-30185997, 32); -- sfix32_En32
  CONSTANT coeffphase1_20                 : signed(31 DOWNTO 0) := to_signed(35325562, 32); -- sfix32_En32
  CONSTANT coeffphase1_21                 : signed(31 DOWNTO 0) := to_signed(-40684362, 32); -- sfix32_En32
  CONSTANT coeffphase1_22                 : signed(31 DOWNTO 0) := to_signed(46172569, 32); -- sfix32_En32
  CONSTANT coeffphase1_23                 : signed(31 DOWNTO 0) := to_signed(-51690797, 32); -- sfix32_En32
  CONSTANT coeffphase1_24                 : signed(31 DOWNTO 0) := to_signed(57132813, 32); -- sfix32_En32
  CONSTANT coeffphase1_25                 : signed(31 DOWNTO 0) := to_signed(-62388577, 32); -- sfix32_En32
  CONSTANT coeffphase1_26                 : signed(31 DOWNTO 0) := to_signed(67347502, 32); -- sfix32_En32
  CONSTANT coeffphase1_27                 : signed(31 DOWNTO 0) := to_signed(-71901819, 32); -- sfix32_En32
  CONSTANT coeffphase1_28                 : signed(31 DOWNTO 0) := to_signed(75949921, 32); -- sfix32_En32
  CONSTANT coeffphase1_29                 : signed(31 DOWNTO 0) := to_signed(-79399565, 32); -- sfix32_En32
  CONSTANT coeffphase1_30                 : signed(31 DOWNTO 0) := to_signed(82170823, 32); -- sfix32_En32
  CONSTANT coeffphase1_31                 : signed(31 DOWNTO 0) := to_signed(-84198652, 32); -- sfix32_En32
  CONSTANT coeffphase1_32                 : signed(31 DOWNTO 0) := to_signed(85435017, 32); -- sfix32_En32
  CONSTANT coeffphase1_33                 : signed(31 DOWNTO 0) := to_signed(2060410771, 32); -- sfix32_En32
  CONSTANT coeffphase1_34                 : signed(31 DOWNTO 0) := to_signed(85435017, 32); -- sfix32_En32
  CONSTANT coeffphase1_35                 : signed(31 DOWNTO 0) := to_signed(-84198652, 32); -- sfix32_En32
  CONSTANT coeffphase1_36                 : signed(31 DOWNTO 0) := to_signed(82170823, 32); -- sfix32_En32
  CONSTANT coeffphase1_37                 : signed(31 DOWNTO 0) := to_signed(-79399565, 32); -- sfix32_En32
  CONSTANT coeffphase1_38                 : signed(31 DOWNTO 0) := to_signed(75949921, 32); -- sfix32_En32
  CONSTANT coeffphase1_39                 : signed(31 DOWNTO 0) := to_signed(-71901819, 32); -- sfix32_En32
  CONSTANT coeffphase1_40                 : signed(31 DOWNTO 0) := to_signed(67347502, 32); -- sfix32_En32
  CONSTANT coeffphase1_41                 : signed(31 DOWNTO 0) := to_signed(-62388577, 32); -- sfix32_En32
  CONSTANT coeffphase1_42                 : signed(31 DOWNTO 0) := to_signed(57132813, 32); -- sfix32_En32
  CONSTANT coeffphase1_43                 : signed(31 DOWNTO 0) := to_signed(-51690797, 32); -- sfix32_En32
  CONSTANT coeffphase1_44                 : signed(31 DOWNTO 0) := to_signed(46172569, 32); -- sfix32_En32
  CONSTANT coeffphase1_45                 : signed(31 DOWNTO 0) := to_signed(-40684362, 32); -- sfix32_En32
  CONSTANT coeffphase1_46                 : signed(31 DOWNTO 0) := to_signed(35325562, 32); -- sfix32_En32
  CONSTANT coeffphase1_47                 : signed(31 DOWNTO 0) := to_signed(-30185997, 32); -- sfix32_En32
  CONSTANT coeffphase1_48                 : signed(31 DOWNTO 0) := to_signed(25343633, 32); -- sfix32_En32
  CONSTANT coeffphase1_49                 : signed(31 DOWNTO 0) := to_signed(-20862774, 32); -- sfix32_En32
  CONSTANT coeffphase1_50                 : signed(31 DOWNTO 0) := to_signed(16792796, 32); -- sfix32_En32
  CONSTANT coeffphase1_51                 : signed(31 DOWNTO 0) := to_signed(-13167465, 32); -- sfix32_En32
  CONSTANT coeffphase1_52                 : signed(31 DOWNTO 0) := to_signed(10004835, 32); -- sfix32_En32
  CONSTANT coeffphase1_53                 : signed(31 DOWNTO 0) := to_signed(-7307718, 32); -- sfix32_En32
  CONSTANT coeffphase1_54                 : signed(31 DOWNTO 0) := to_signed(5064688, 32); -- sfix32_En32
  CONSTANT coeffphase1_55                 : signed(31 DOWNTO 0) := to_signed(-3251561, 32); -- sfix32_En32
  CONSTANT coeffphase1_56                 : signed(31 DOWNTO 0) := to_signed(1833277, 32); -- sfix32_En32
  CONSTANT coeffphase1_57                 : signed(31 DOWNTO 0) := to_signed(-766094, 32); -- sfix32_En32
  CONSTANT coeffphase1_58                 : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeffphase1_59                 : signed(31 DOWNTO 0) := to_signed(518767, 32); -- sfix32_En32
  CONSTANT coeffphase1_60                 : signed(31 DOWNTO 0) := to_signed(-845192, 32); -- sfix32_En32
  CONSTANT coeffphase1_61                 : signed(31 DOWNTO 0) := to_signed(1033060, 32); -- sfix32_En32
  CONSTANT coeffphase1_62                 : signed(31 DOWNTO 0) := to_signed(-1132720, 32); -- sfix32_En32
  CONSTANT coeffphase1_63                 : signed(31 DOWNTO 0) := to_signed(1189139, 32); -- sfix32_En32
  CONSTANT coeffphase1_64                 : signed(31 DOWNTO 0) := to_signed(-1240297, 32); -- sfix32_En32
  CONSTANT coeffphase1_65                 : signed(31 DOWNTO 0) := to_signed(1315991, 32); -- sfix32_En32
  CONSTANT coeffphase2_1                  : signed(31 DOWNTO 0) := to_signed(1195950, 32); -- sfix32_En32
  CONSTANT coeffphase2_2                  : signed(31 DOWNTO 0) := to_signed(-1466640, 32); -- sfix32_En32
  CONSTANT coeffphase2_3                  : signed(31 DOWNTO 0) := to_signed(1833826, 32); -- sfix32_En32
  CONSTANT coeffphase2_4                  : signed(31 DOWNTO 0) := to_signed(-2318406, 32); -- sfix32_En32
  CONSTANT coeffphase2_5                  : signed(31 DOWNTO 0) := to_signed(2933630, 32); -- sfix32_En32
  CONSTANT coeffphase2_6                  : signed(31 DOWNTO 0) := to_signed(-3683186, 32); -- sfix32_En32
  CONSTANT coeffphase2_7                  : signed(31 DOWNTO 0) := to_signed(4559546, 32); -- sfix32_En32
  CONSTANT coeffphase2_8                  : signed(31 DOWNTO 0) := to_signed(-5542636, 32); -- sfix32_En32
  CONSTANT coeffphase2_9                  : signed(31 DOWNTO 0) := to_signed(6598894, 32); -- sfix32_En32
  CONSTANT coeffphase2_10                 : signed(31 DOWNTO 0) := to_signed(-7680734, 32); -- sfix32_En32
  CONSTANT coeffphase2_11                 : signed(31 DOWNTO 0) := to_signed(8726433, 32); -- sfix32_En32
  CONSTANT coeffphase2_12                 : signed(31 DOWNTO 0) := to_signed(-9660397, 32); -- sfix32_En32
  CONSTANT coeffphase2_13                 : signed(31 DOWNTO 0) := to_signed(10393780, 32); -- sfix32_En32
  CONSTANT coeffphase2_14                 : signed(31 DOWNTO 0) := to_signed(-10825314, 32); -- sfix32_En32
  CONSTANT coeffphase2_15                 : signed(31 DOWNTO 0) := to_signed(10842235, 32); -- sfix32_En32
  CONSTANT coeffphase2_16                 : signed(31 DOWNTO 0) := to_signed(-10321064, 32); -- sfix32_En32
  CONSTANT coeffphase2_17                 : signed(31 DOWNTO 0) := to_signed(9127950, 32); -- sfix32_En32
  CONSTANT coeffphase2_18                 : signed(31 DOWNTO 0) := to_signed(-7118136, 32); -- sfix32_En32
  CONSTANT coeffphase2_19                 : signed(31 DOWNTO 0) := to_signed(4133902, 32); -- sfix32_En32
  CONSTANT coeffphase2_20                 : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeffphase2_21                 : signed(31 DOWNTO 0) := to_signed(-5485008, 32); -- sfix32_En32
  CONSTANT coeffphase2_22                 : signed(31 DOWNTO 0) := to_signed(12564230, 32); -- sfix32_En32
  CONSTANT coeffphase2_23                 : signed(31 DOWNTO 0) := to_signed(-21549632, 32); -- sfix32_En32
  CONSTANT coeffphase2_24                 : signed(31 DOWNTO 0) := to_signed(32870333, 32); -- sfix32_En32
  CONSTANT coeffphase2_25                 : signed(31 DOWNTO 0) := to_signed(-47161318, 32); -- sfix32_En32
  CONSTANT coeffphase2_26                 : signed(31 DOWNTO 0) := to_signed(65435538, 32); -- sfix32_En32
  CONSTANT coeffphase2_27                 : signed(31 DOWNTO 0) := to_signed(-89444793, 32); -- sfix32_En32
  CONSTANT coeffphase2_28                 : signed(31 DOWNTO 0) := to_signed(122522065, 32); -- sfix32_En32
  CONSTANT coeffphase2_29                 : signed(31 DOWNTO 0) := to_signed(-171866920, 32); -- sfix32_En32
  CONSTANT coeffphase2_30                 : signed(31 DOWNTO 0) := to_signed(256312834, 32); -- sfix32_En32
  CONSTANT coeffphase2_31                 : signed(31 DOWNTO 0) := to_signed(-445156056, 32); -- sfix32_En32
  CONSTANT coeffphase2_32                 : signed(31 DOWNTO 0) := to_signed(1362900556, 32); -- sfix32_En32
  CONSTANT coeffphase2_33                 : signed(31 DOWNTO 0) := to_signed(1362900556, 32); -- sfix32_En32
  CONSTANT coeffphase2_34                 : signed(31 DOWNTO 0) := to_signed(-445156056, 32); -- sfix32_En32
  CONSTANT coeffphase2_35                 : signed(31 DOWNTO 0) := to_signed(256312834, 32); -- sfix32_En32
  CONSTANT coeffphase2_36                 : signed(31 DOWNTO 0) := to_signed(-171866920, 32); -- sfix32_En32
  CONSTANT coeffphase2_37                 : signed(31 DOWNTO 0) := to_signed(122522065, 32); -- sfix32_En32
  CONSTANT coeffphase2_38                 : signed(31 DOWNTO 0) := to_signed(-89444793, 32); -- sfix32_En32
  CONSTANT coeffphase2_39                 : signed(31 DOWNTO 0) := to_signed(65435538, 32); -- sfix32_En32
  CONSTANT coeffphase2_40                 : signed(31 DOWNTO 0) := to_signed(-47161318, 32); -- sfix32_En32
  CONSTANT coeffphase2_41                 : signed(31 DOWNTO 0) := to_signed(32870333, 32); -- sfix32_En32
  CONSTANT coeffphase2_42                 : signed(31 DOWNTO 0) := to_signed(-21549632, 32); -- sfix32_En32
  CONSTANT coeffphase2_43                 : signed(31 DOWNTO 0) := to_signed(12564230, 32); -- sfix32_En32
  CONSTANT coeffphase2_44                 : signed(31 DOWNTO 0) := to_signed(-5485008, 32); -- sfix32_En32
  CONSTANT coeffphase2_45                 : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32
  CONSTANT coeffphase2_46                 : signed(31 DOWNTO 0) := to_signed(4133902, 32); -- sfix32_En32
  CONSTANT coeffphase2_47                 : signed(31 DOWNTO 0) := to_signed(-7118136, 32); -- sfix32_En32
  CONSTANT coeffphase2_48                 : signed(31 DOWNTO 0) := to_signed(9127950, 32); -- sfix32_En32
  CONSTANT coeffphase2_49                 : signed(31 DOWNTO 0) := to_signed(-10321064, 32); -- sfix32_En32
  CONSTANT coeffphase2_50                 : signed(31 DOWNTO 0) := to_signed(10842235, 32); -- sfix32_En32
  CONSTANT coeffphase2_51                 : signed(31 DOWNTO 0) := to_signed(-10825314, 32); -- sfix32_En32
  CONSTANT coeffphase2_52                 : signed(31 DOWNTO 0) := to_signed(10393780, 32); -- sfix32_En32
  CONSTANT coeffphase2_53                 : signed(31 DOWNTO 0) := to_signed(-9660397, 32); -- sfix32_En32
  CONSTANT coeffphase2_54                 : signed(31 DOWNTO 0) := to_signed(8726433, 32); -- sfix32_En32
  CONSTANT coeffphase2_55                 : signed(31 DOWNTO 0) := to_signed(-7680734, 32); -- sfix32_En32
  CONSTANT coeffphase2_56                 : signed(31 DOWNTO 0) := to_signed(6598894, 32); -- sfix32_En32
  CONSTANT coeffphase2_57                 : signed(31 DOWNTO 0) := to_signed(-5542636, 32); -- sfix32_En32
  CONSTANT coeffphase2_58                 : signed(31 DOWNTO 0) := to_signed(4559546, 32); -- sfix32_En32
  CONSTANT coeffphase2_59                 : signed(31 DOWNTO 0) := to_signed(-3683186, 32); -- sfix32_En32
  CONSTANT coeffphase2_60                 : signed(31 DOWNTO 0) := to_signed(2933630, 32); -- sfix32_En32
  CONSTANT coeffphase2_61                 : signed(31 DOWNTO 0) := to_signed(-2318406, 32); -- sfix32_En32
  CONSTANT coeffphase2_62                 : signed(31 DOWNTO 0) := to_signed(1833826, 32); -- sfix32_En32
  CONSTANT coeffphase2_63                 : signed(31 DOWNTO 0) := to_signed(-1466640, 32); -- sfix32_En32
  CONSTANT coeffphase2_64                 : signed(31 DOWNTO 0) := to_signed(1195950, 32); -- sfix32_En32
  CONSTANT coeffphase2_65                 : signed(31 DOWNTO 0) := to_signed(0, 32); -- sfix32_En32

  CONSTANT const_zero                     : signed(64 DOWNTO 0) := to_signed(0, 65); -- sfix65_En60
  -- Signals
  SIGNAL cur_count                        : unsigned(4 DOWNTO 0); -- ufix5
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL phase_16                         : std_logic; -- boolean
  SIGNAL phase_16_1                       : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 64); -- sfix32_En28
  SIGNAL tapsum_and                       : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_1                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_2                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_3                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_4                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_5                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_6                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_7                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_8                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_9                     : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_10                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_11                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_12                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_13                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_14                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_15                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_16                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_17                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_18                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_19                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_20                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_21                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_22                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_23                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_24                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_25                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_26                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_27                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_28                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_29                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_30                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_31                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_32                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_33                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_34                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_35                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_36                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_37                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_38                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_39                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_40                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_41                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_42                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_43                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_44                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_45                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_46                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_47                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_48                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_49                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_50                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_51                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_52                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_53                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_54                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_55                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_56                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_57                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_58                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_59                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_60                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL tapsum_and_61                    : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL inputmux                         : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL delay_pipeline32_cast            : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL inputmux_1                       : signed(32 DOWNTO 0); -- sfix33_En28
  SIGNAL product1                         : signed(64 DOWNTO 0); -- sfix65_En60
  SIGNAL product1_mux                     : signed(31 DOWNTO 0); -- sfix32_En32
  SIGNAL product2                         : signed(64 DOWNTO 0); -- sfix65_En60
  SIGNAL product2_mux                     : signed(31 DOWNTO 0); -- sfix32_En32
  SIGNAL phasemux                         : signed(64 DOWNTO 0); -- sfix65_En60
  SIGNAL sumofproducts                    : signed(65 DOWNTO 0); -- sfix66_En60
  SIGNAL sumofproducts_cast               : signed(80 DOWNTO 0); -- sfix81_En60
  SIGNAL acc_sum                          : signed(80 DOWNTO 0); -- sfix81_En60
  SIGNAL accreg_in                        : signed(80 DOWNTO 0); -- sfix81_En60
  SIGNAL accreg_out                       : signed(80 DOWNTO 0); -- sfix81_En60
  SIGNAL add_temp                         : signed(81 DOWNTO 0); -- sfix82_En60
  SIGNAL accreg_final                     : signed(80 DOWNTO 0); -- sfix81_En60
  SIGNAL output_typeconvert               : signed(70 DOWNTO 0); -- sfix71_En60
  SIGNAL output_register                  : signed(70 DOWNTO 0); -- sfix71_En60


BEGIN

  -- Block Statements
  Counter : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(31, 5);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count = to_unsigned(31, 5) THEN
          cur_count <= to_unsigned(0, 5);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 5);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter;

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 5) AND clk_enable = '1' ELSE '0';

  phase_1 <= '1' WHEN  (((cur_count = to_unsigned(1, 5))  OR
                         (cur_count = to_unsigned(2, 5))  OR
                         (cur_count = to_unsigned(3, 5))  OR
                         (cur_count = to_unsigned(4, 5))  OR
                         (cur_count = to_unsigned(5, 5))  OR
                         (cur_count = to_unsigned(6, 5))  OR
                         (cur_count = to_unsigned(7, 5))  OR
                         (cur_count = to_unsigned(8, 5))  OR
                         (cur_count = to_unsigned(9, 5))  OR
                         (cur_count = to_unsigned(10, 5))  OR
                         (cur_count = to_unsigned(11, 5))  OR
                         (cur_count = to_unsigned(12, 5))  OR
                         (cur_count = to_unsigned(13, 5))  OR
                         (cur_count = to_unsigned(14, 5))  OR
                         (cur_count = to_unsigned(15, 5))  OR
                         (cur_count = to_unsigned(16, 5))  OR
                         (cur_count = to_unsigned(17, 5))  OR
                         (cur_count = to_unsigned(18, 5))  OR
                         (cur_count = to_unsigned(19, 5))  OR
                         (cur_count = to_unsigned(20, 5))  OR
                         (cur_count = to_unsigned(21, 5))  OR
                         (cur_count = to_unsigned(22, 5))  OR
                         (cur_count = to_unsigned(23, 5))  OR
                         (cur_count = to_unsigned(24, 5))  OR
                         (cur_count = to_unsigned(25, 5))  OR
                         (cur_count = to_unsigned(26, 5))  OR
                         (cur_count = to_unsigned(27, 5))  OR
                         (cur_count = to_unsigned(28, 5))  OR
                         (cur_count = to_unsigned(29, 5))  OR
                         (cur_count = to_unsigned(30, 5))  OR
                         (cur_count = to_unsigned(31, 5)))  AND clk_enable = '1') ELSE '0';

  phase_16 <= '1' WHEN  (((cur_count = to_unsigned(17, 5))  OR
                          (cur_count = to_unsigned(1, 5)))  AND clk_enable = '1') ELSE '0';

  phase_16_1 <= '1' WHEN  (((cur_count = to_unsigned(18, 5))  OR
                            (cur_count = to_unsigned(2, 5)))  AND clk_enable = '1') ELSE '0';

  --   ---------------- Delay Registers ----------------

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 64) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 64) <= delay_pipeline(0 TO 63);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  -- Adding (or subtracting) the taps based on the symmetry (or asymmetry)

  tapsum_and <= resize(delay_pipeline(6), 33) + resize(delay_pipeline(58), 33);

  tapsum_and_1 <= resize(delay_pipeline(8), 33) + resize(delay_pipeline(56), 33);

  tapsum_and_2 <= resize(delay_pipeline(5), 33) + resize(delay_pipeline(59), 33);

  tapsum_and_3 <= resize(delay_pipeline(4), 33) + resize(delay_pipeline(60), 33);

  tapsum_and_4 <= resize(delay_pipeline(3), 33) + resize(delay_pipeline(61), 33);

  tapsum_and_5 <= resize(delay_pipeline(2), 33) + resize(delay_pipeline(62), 33);

  tapsum_and_6 <= resize(delay_pipeline(1), 33) + resize(delay_pipeline(63), 33);

  tapsum_and_7 <= resize(delay_pipeline(0), 33) + resize(delay_pipeline(64), 33);

  tapsum_and_8 <= resize(delay_pipeline(9), 33) + resize(delay_pipeline(55), 33);

  tapsum_and_9 <= resize(delay_pipeline(10), 33) + resize(delay_pipeline(54), 33);

  tapsum_and_10 <= resize(delay_pipeline(11), 33) + resize(delay_pipeline(53), 33);

  tapsum_and_11 <= resize(delay_pipeline(12), 33) + resize(delay_pipeline(52), 33);

  tapsum_and_12 <= resize(delay_pipeline(13), 33) + resize(delay_pipeline(51), 33);

  tapsum_and_13 <= resize(delay_pipeline(14), 33) + resize(delay_pipeline(50), 33);

  tapsum_and_14 <= resize(delay_pipeline(15), 33) + resize(delay_pipeline(49), 33);

  tapsum_and_15 <= resize(delay_pipeline(16), 33) + resize(delay_pipeline(48), 33);

  tapsum_and_16 <= resize(delay_pipeline(17), 33) + resize(delay_pipeline(47), 33);

  tapsum_and_17 <= resize(delay_pipeline(18), 33) + resize(delay_pipeline(46), 33);

  tapsum_and_18 <= resize(delay_pipeline(19), 33) + resize(delay_pipeline(45), 33);

  tapsum_and_19 <= resize(delay_pipeline(20), 33) + resize(delay_pipeline(44), 33);

  tapsum_and_20 <= resize(delay_pipeline(21), 33) + resize(delay_pipeline(43), 33);

  tapsum_and_21 <= resize(delay_pipeline(22), 33) + resize(delay_pipeline(42), 33);

  tapsum_and_22 <= resize(delay_pipeline(23), 33) + resize(delay_pipeline(41), 33);

  tapsum_and_23 <= resize(delay_pipeline(24), 33) + resize(delay_pipeline(40), 33);

  tapsum_and_24 <= resize(delay_pipeline(25), 33) + resize(delay_pipeline(39), 33);

  tapsum_and_25 <= resize(delay_pipeline(26), 33) + resize(delay_pipeline(38), 33);

  tapsum_and_26 <= resize(delay_pipeline(27), 33) + resize(delay_pipeline(37), 33);

  tapsum_and_27 <= resize(delay_pipeline(28), 33) + resize(delay_pipeline(36), 33);

  tapsum_and_28 <= resize(delay_pipeline(29), 33) + resize(delay_pipeline(35), 33);

  tapsum_and_29 <= resize(delay_pipeline(30), 33) + resize(delay_pipeline(34), 33);

  tapsum_and_30 <= resize(delay_pipeline(31), 33) + resize(delay_pipeline(33), 33);

  tapsum_and_31 <= resize(delay_pipeline(0), 33) + resize(delay_pipeline(63), 33);

  tapsum_and_32 <= resize(delay_pipeline(1), 33) + resize(delay_pipeline(62), 33);

  tapsum_and_33 <= resize(delay_pipeline(2), 33) + resize(delay_pipeline(61), 33);

  tapsum_and_34 <= resize(delay_pipeline(3), 33) + resize(delay_pipeline(60), 33);

  tapsum_and_35 <= resize(delay_pipeline(4), 33) + resize(delay_pipeline(59), 33);

  tapsum_and_36 <= resize(delay_pipeline(5), 33) + resize(delay_pipeline(58), 33);

  tapsum_and_37 <= resize(delay_pipeline(18), 33) + resize(delay_pipeline(45), 33);

  tapsum_and_38 <= resize(delay_pipeline(6), 33) + resize(delay_pipeline(57), 33);

  tapsum_and_39 <= resize(delay_pipeline(20), 33) + resize(delay_pipeline(43), 33);

  tapsum_and_40 <= resize(delay_pipeline(7), 33) + resize(delay_pipeline(56), 33);

  tapsum_and_41 <= resize(delay_pipeline(8), 33) + resize(delay_pipeline(55), 33);

  tapsum_and_42 <= resize(delay_pipeline(17), 33) + resize(delay_pipeline(46), 33);

  tapsum_and_43 <= resize(delay_pipeline(9), 33) + resize(delay_pipeline(54), 33);

  tapsum_and_44 <= resize(delay_pipeline(10), 33) + resize(delay_pipeline(53), 33);

  tapsum_and_45 <= resize(delay_pipeline(16), 33) + resize(delay_pipeline(47), 33);

  tapsum_and_46 <= resize(delay_pipeline(11), 33) + resize(delay_pipeline(52), 33);

  tapsum_and_47 <= resize(delay_pipeline(15), 33) + resize(delay_pipeline(48), 33);

  tapsum_and_48 <= resize(delay_pipeline(12), 33) + resize(delay_pipeline(51), 33);

  tapsum_and_49 <= resize(delay_pipeline(13), 33) + resize(delay_pipeline(50), 33);

  tapsum_and_50 <= resize(delay_pipeline(14), 33) + resize(delay_pipeline(49), 33);

  tapsum_and_51 <= resize(delay_pipeline(21), 33) + resize(delay_pipeline(42), 33);

  tapsum_and_52 <= resize(delay_pipeline(22), 33) + resize(delay_pipeline(41), 33);

  tapsum_and_53 <= resize(delay_pipeline(23), 33) + resize(delay_pipeline(40), 33);

  tapsum_and_54 <= resize(delay_pipeline(24), 33) + resize(delay_pipeline(39), 33);

  tapsum_and_55 <= resize(delay_pipeline(25), 33) + resize(delay_pipeline(38), 33);

  tapsum_and_56 <= resize(delay_pipeline(26), 33) + resize(delay_pipeline(37), 33);

  tapsum_and_57 <= resize(delay_pipeline(27), 33) + resize(delay_pipeline(36), 33);

  tapsum_and_58 <= resize(delay_pipeline(28), 33) + resize(delay_pipeline(35), 33);

  tapsum_and_59 <= resize(delay_pipeline(29), 33) + resize(delay_pipeline(34), 33);

  tapsum_and_60 <= resize(delay_pipeline(30), 33) + resize(delay_pipeline(33), 33);

  tapsum_and_61 <= resize(delay_pipeline(31), 33) + resize(delay_pipeline(32), 33);

  -- Mux(es) to select the input taps for multipliers 

  inputmux <= tapsum_and_7 WHEN ( cur_count = to_unsigned(1, 5) ) ELSE
                   tapsum_and_5 WHEN ( cur_count = to_unsigned(2, 5) ) ELSE
                   tapsum_and_3 WHEN ( cur_count = to_unsigned(3, 5) ) ELSE
                   tapsum_and WHEN ( cur_count = to_unsigned(4, 5) ) ELSE
                   tapsum_and_8 WHEN ( cur_count = to_unsigned(5, 5) ) ELSE
                   tapsum_and_10 WHEN ( cur_count = to_unsigned(6, 5) ) ELSE
                   tapsum_and_12 WHEN ( cur_count = to_unsigned(7, 5) ) ELSE
                   tapsum_and_14 WHEN ( cur_count = to_unsigned(8, 5) ) ELSE
                   tapsum_and_16 WHEN ( cur_count = to_unsigned(9, 5) ) ELSE
                   tapsum_and_18 WHEN ( cur_count = to_unsigned(10, 5) ) ELSE
                   tapsum_and_20 WHEN ( cur_count = to_unsigned(11, 5) ) ELSE
                   tapsum_and_22 WHEN ( cur_count = to_unsigned(12, 5) ) ELSE
                   tapsum_and_24 WHEN ( cur_count = to_unsigned(13, 5) ) ELSE
                   tapsum_and_26 WHEN ( cur_count = to_unsigned(14, 5) ) ELSE
                   tapsum_and_28 WHEN ( cur_count = to_unsigned(15, 5) ) ELSE
                   tapsum_and_30 WHEN ( cur_count = to_unsigned(16, 5) ) ELSE
                   tapsum_and_31 WHEN ( cur_count = to_unsigned(17, 5) ) ELSE
                   tapsum_and_33 WHEN ( cur_count = to_unsigned(18, 5) ) ELSE
                   tapsum_and_35 WHEN ( cur_count = to_unsigned(19, 5) ) ELSE
                   tapsum_and_38 WHEN ( cur_count = to_unsigned(20, 5) ) ELSE
                   tapsum_and_41 WHEN ( cur_count = to_unsigned(21, 5) ) ELSE
                   tapsum_and_44 WHEN ( cur_count = to_unsigned(22, 5) ) ELSE
                   tapsum_and_48 WHEN ( cur_count = to_unsigned(23, 5) ) ELSE
                   tapsum_and_50 WHEN ( cur_count = to_unsigned(24, 5) ) ELSE
                   tapsum_and_45 WHEN ( cur_count = to_unsigned(25, 5) ) ELSE
                   tapsum_and_37 WHEN ( cur_count = to_unsigned(26, 5) ) ELSE
                   tapsum_and_51 WHEN ( cur_count = to_unsigned(27, 5) ) ELSE
                   tapsum_and_53 WHEN ( cur_count = to_unsigned(28, 5) ) ELSE
                   tapsum_and_55 WHEN ( cur_count = to_unsigned(29, 5) ) ELSE
                   tapsum_and_57 WHEN ( cur_count = to_unsigned(30, 5) ) ELSE
                   tapsum_and_59 WHEN ( cur_count = to_unsigned(31, 5) ) ELSE
                   tapsum_and_61;

  delay_pipeline32_cast <= resize(delay_pipeline(32), 33);

  inputmux_1 <= tapsum_and_6 WHEN ( cur_count = to_unsigned(1, 5) ) ELSE
                     tapsum_and_4 WHEN ( cur_count = to_unsigned(2, 5) ) ELSE
                     tapsum_and_2 WHEN ( cur_count = to_unsigned(3, 5) ) ELSE
                     tapsum_and_1 WHEN ( cur_count = to_unsigned(4, 5) ) ELSE
                     tapsum_and_9 WHEN ( cur_count = to_unsigned(5, 5) ) ELSE
                     tapsum_and_11 WHEN ( cur_count = to_unsigned(6, 5) ) ELSE
                     tapsum_and_13 WHEN ( cur_count = to_unsigned(7, 5) ) ELSE
                     tapsum_and_15 WHEN ( cur_count = to_unsigned(8, 5) ) ELSE
                     tapsum_and_17 WHEN ( cur_count = to_unsigned(9, 5) ) ELSE
                     tapsum_and_19 WHEN ( cur_count = to_unsigned(10, 5) ) ELSE
                     tapsum_and_21 WHEN ( cur_count = to_unsigned(11, 5) ) ELSE
                     tapsum_and_23 WHEN ( cur_count = to_unsigned(12, 5) ) ELSE
                     tapsum_and_25 WHEN ( cur_count = to_unsigned(13, 5) ) ELSE
                     tapsum_and_27 WHEN ( cur_count = to_unsigned(14, 5) ) ELSE
                     tapsum_and_29 WHEN ( cur_count = to_unsigned(15, 5) ) ELSE
                     delay_pipeline32_cast WHEN ( cur_count = to_unsigned(16, 5) ) ELSE
                     tapsum_and_32 WHEN ( cur_count = to_unsigned(17, 5) ) ELSE
                     tapsum_and_34 WHEN ( cur_count = to_unsigned(18, 5) ) ELSE
                     tapsum_and_36 WHEN ( cur_count = to_unsigned(19, 5) ) ELSE
                     tapsum_and_40 WHEN ( cur_count = to_unsigned(20, 5) ) ELSE
                     tapsum_and_43 WHEN ( cur_count = to_unsigned(21, 5) ) ELSE
                     tapsum_and_46 WHEN ( cur_count = to_unsigned(22, 5) ) ELSE
                     tapsum_and_49 WHEN ( cur_count = to_unsigned(23, 5) ) ELSE
                     tapsum_and_47 WHEN ( cur_count = to_unsigned(24, 5) ) ELSE
                     tapsum_and_42 WHEN ( cur_count = to_unsigned(25, 5) ) ELSE
                     tapsum_and_39 WHEN ( cur_count = to_unsigned(26, 5) ) ELSE
                     tapsum_and_52 WHEN ( cur_count = to_unsigned(27, 5) ) ELSE
                     tapsum_and_54 WHEN ( cur_count = to_unsigned(28, 5) ) ELSE
                     tapsum_and_56 WHEN ( cur_count = to_unsigned(29, 5) ) ELSE
                     tapsum_and_58 WHEN ( cur_count = to_unsigned(30, 5) ) ELSE
                     tapsum_and_60;

  product1_mux <= coeffphase1_1 WHEN ( cur_count = to_unsigned(1, 5) ) ELSE
                       coeffphase1_3 WHEN ( cur_count = to_unsigned(2, 5) ) ELSE
                       coeffphase1_5 WHEN ( cur_count = to_unsigned(3, 5) ) ELSE
                       coeffphase1_7 WHEN ( cur_count = to_unsigned(4, 5) ) ELSE
                       coeffphase1_10 WHEN ( cur_count = to_unsigned(5, 5) ) ELSE
                       coeffphase1_12 WHEN ( cur_count = to_unsigned(6, 5) ) ELSE
                       coeffphase1_14 WHEN ( cur_count = to_unsigned(7, 5) ) ELSE
                       coeffphase1_16 WHEN ( cur_count = to_unsigned(8, 5) ) ELSE
                       coeffphase1_18 WHEN ( cur_count = to_unsigned(9, 5) ) ELSE
                       coeffphase1_20 WHEN ( cur_count = to_unsigned(10, 5) ) ELSE
                       coeffphase1_22 WHEN ( cur_count = to_unsigned(11, 5) ) ELSE
                       coeffphase1_24 WHEN ( cur_count = to_unsigned(12, 5) ) ELSE
                       coeffphase1_26 WHEN ( cur_count = to_unsigned(13, 5) ) ELSE
                       coeffphase1_28 WHEN ( cur_count = to_unsigned(14, 5) ) ELSE
                       coeffphase1_30 WHEN ( cur_count = to_unsigned(15, 5) ) ELSE
                       coeffphase1_32 WHEN ( cur_count = to_unsigned(16, 5) ) ELSE
                       coeffphase2_1 WHEN ( cur_count = to_unsigned(17, 5) ) ELSE
                       coeffphase2_3 WHEN ( cur_count = to_unsigned(18, 5) ) ELSE
                       coeffphase2_5 WHEN ( cur_count = to_unsigned(19, 5) ) ELSE
                       coeffphase2_7 WHEN ( cur_count = to_unsigned(20, 5) ) ELSE
                       coeffphase2_9 WHEN ( cur_count = to_unsigned(21, 5) ) ELSE
                       coeffphase2_11 WHEN ( cur_count = to_unsigned(22, 5) ) ELSE
                       coeffphase2_13 WHEN ( cur_count = to_unsigned(23, 5) ) ELSE
                       coeffphase2_15 WHEN ( cur_count = to_unsigned(24, 5) ) ELSE
                       coeffphase2_17 WHEN ( cur_count = to_unsigned(25, 5) ) ELSE
                       coeffphase2_19 WHEN ( cur_count = to_unsigned(26, 5) ) ELSE
                       coeffphase2_22 WHEN ( cur_count = to_unsigned(27, 5) ) ELSE
                       coeffphase2_24 WHEN ( cur_count = to_unsigned(28, 5) ) ELSE
                       coeffphase2_26 WHEN ( cur_count = to_unsigned(29, 5) ) ELSE
                       coeffphase2_28 WHEN ( cur_count = to_unsigned(30, 5) ) ELSE
                       coeffphase2_30 WHEN ( cur_count = to_unsigned(31, 5) ) ELSE
                       coeffphase2_32;
  product1 <= inputmux * product1_mux;

  product2_mux <= coeffphase1_2 WHEN ( cur_count = to_unsigned(1, 5) ) ELSE
                       coeffphase1_4 WHEN ( cur_count = to_unsigned(2, 5) ) ELSE
                       coeffphase1_6 WHEN ( cur_count = to_unsigned(3, 5) ) ELSE
                       coeffphase1_9 WHEN ( cur_count = to_unsigned(4, 5) ) ELSE
                       coeffphase1_11 WHEN ( cur_count = to_unsigned(5, 5) ) ELSE
                       coeffphase1_13 WHEN ( cur_count = to_unsigned(6, 5) ) ELSE
                       coeffphase1_15 WHEN ( cur_count = to_unsigned(7, 5) ) ELSE
                       coeffphase1_17 WHEN ( cur_count = to_unsigned(8, 5) ) ELSE
                       coeffphase1_19 WHEN ( cur_count = to_unsigned(9, 5) ) ELSE
                       coeffphase1_21 WHEN ( cur_count = to_unsigned(10, 5) ) ELSE
                       coeffphase1_23 WHEN ( cur_count = to_unsigned(11, 5) ) ELSE
                       coeffphase1_25 WHEN ( cur_count = to_unsigned(12, 5) ) ELSE
                       coeffphase1_27 WHEN ( cur_count = to_unsigned(13, 5) ) ELSE
                       coeffphase1_29 WHEN ( cur_count = to_unsigned(14, 5) ) ELSE
                       coeffphase1_31 WHEN ( cur_count = to_unsigned(15, 5) ) ELSE
                       coeffphase1_33 WHEN ( cur_count = to_unsigned(16, 5) ) ELSE
                       coeffphase2_2 WHEN ( cur_count = to_unsigned(17, 5) ) ELSE
                       coeffphase2_4 WHEN ( cur_count = to_unsigned(18, 5) ) ELSE
                       coeffphase2_6 WHEN ( cur_count = to_unsigned(19, 5) ) ELSE
                       coeffphase2_8 WHEN ( cur_count = to_unsigned(20, 5) ) ELSE
                       coeffphase2_10 WHEN ( cur_count = to_unsigned(21, 5) ) ELSE
                       coeffphase2_12 WHEN ( cur_count = to_unsigned(22, 5) ) ELSE
                       coeffphase2_14 WHEN ( cur_count = to_unsigned(23, 5) ) ELSE
                       coeffphase2_16 WHEN ( cur_count = to_unsigned(24, 5) ) ELSE
                       coeffphase2_18 WHEN ( cur_count = to_unsigned(25, 5) ) ELSE
                       coeffphase2_21 WHEN ( cur_count = to_unsigned(26, 5) ) ELSE
                       coeffphase2_23 WHEN ( cur_count = to_unsigned(27, 5) ) ELSE
                       coeffphase2_25 WHEN ( cur_count = to_unsigned(28, 5) ) ELSE
                       coeffphase2_27 WHEN ( cur_count = to_unsigned(29, 5) ) ELSE
                       coeffphase2_29 WHEN ( cur_count = to_unsigned(30, 5) ) ELSE
                       coeffphase2_31;
  product2 <= inputmux_1 * product2_mux;

  phasemux <= product2 WHEN ( phase_1 = '1' ) ELSE
                   const_zero;


  -- Add the products in linear fashion

  sumofproducts <= resize(product1, 66) + resize(phasemux, 66);

  -- Resize the sum of products to the accumulator type for full precision addition

  sumofproducts_cast <= resize(sumofproducts, 81);

  -- Accumulator register with a mux to reset it with the first addend

  add_temp <= resize(sumofproducts_cast, 82) + resize(accreg_out, 82);
  acc_sum <= add_temp(80 DOWNTO 0);

  accreg_in <= sumofproducts_cast WHEN ( phase_16 = '1' ) ELSE
                    acc_sum;

  Acc_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accreg_out <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        accreg_out <= accreg_in;
      END IF;
    END IF; 
  END PROCESS Acc_reg_process;

  -- Register to hold the final value of the accumulated sum

  Acc_finalreg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accreg_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_16 = '1' THEN
        accreg_final <= accreg_out;
      END IF;
    END IF; 
  END PROCESS Acc_finalreg_process;

  output_typeconvert <= accreg_final(70 DOWNTO 0);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_16_1 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  ce_out <= phase_0;
  filter_out <= std_logic_vector(output_register);
END rtl;
